/**
 * Public Investor Database
 *
 * All data sourced from publicly available information:
 * - SEC EDGAR 13F filings (sec.gov)
 * - OpenVC database (openvc.app)
 * - Company websites and press releases
 * - LinkedIn public profiles
 * - Crunchbase public data
 * - PitchBook public data
 * - AngelList public profiles
 *
 * Last updated: January 2025
 */

export interface PublicInvestor {
  name: string;
  firm: string;
  type: 'vc' | 'pe' | 'hedge_fund' | 'family_office' | 'angel' | 'cvc' | 'accelerator' | 'institutional';
  aum?: number;
  checkSizeMin?: number;
  checkSizeMax?: number;
  stages: string[];
  sectors: string[];
  location?: { city: string; state?: string; country: string };
  website?: string;
  source: string;
  sourceUrl?: string;
  cik?: string; // SEC CIK number
  linkedinUrl?: string;
  email?: string; // Public contact emails only
  notable_investments?: string[];
}

// ===========================================
// TIER 1 VCs - Top Silicon Valley Funds
// Source: SEC 13F, Company Websites, Crunchbase
// ===========================================

export const TIER1_VCS: PublicInvestor[] = [
  {
    name: 'Andreessen Horowitz',
    firm: 'Andreessen Horowitz (a16z)',
    type: 'vc',
    aum: 35000000000,
    checkSizeMin: 1000000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['software', 'crypto', 'fintech', 'healthcare', 'consumer', 'enterprise'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://a16z.com',
    source: 'SEC EDGAR 13F, Company Website',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001768355',
    cik: '0001768355',
    notable_investments: ['Facebook', 'Airbnb', 'Coinbase', 'Stripe', 'GitHub'],
  },
  {
    name: 'Sequoia Capital',
    firm: 'Sequoia Capital',
    type: 'vc',
    aum: 85000000000,
    checkSizeMin: 100000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['software', 'fintech', 'healthcare', 'consumer', 'enterprise'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://www.sequoiacap.com',
    source: 'SEC EDGAR 13F, Company Website',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001603466',
    cik: '0001603466',
    notable_investments: ['Apple', 'Google', 'WhatsApp', 'Stripe', 'Zoom'],
  },
  {
    name: 'Accel',
    firm: 'Accel Partners',
    type: 'vc',
    aum: 50000000000,
    checkSizeMin: 500000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b'],
    sectors: ['software', 'fintech', 'enterprise', 'consumer'],
    location: { city: 'Palo Alto', state: 'CA', country: 'USA' },
    website: 'https://www.accel.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/accel',
    notable_investments: ['Facebook', 'Dropbox', 'Slack', 'Spotify', 'UiPath'],
  },
  {
    name: 'Benchmark',
    firm: 'Benchmark Capital',
    type: 'vc',
    aum: 4000000000,
    checkSizeMin: 1000000,
    checkSizeMax: 25000000,
    stages: ['seed', 'series_a'],
    sectors: ['software', 'marketplaces', 'consumer', 'enterprise'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://www.benchmark.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/benchmark',
    notable_investments: ['eBay', 'Twitter', 'Uber', 'Snapchat', 'Discord'],
  },
  {
    name: 'Greylock Partners',
    firm: 'Greylock Partners',
    type: 'vc',
    aum: 5000000000,
    checkSizeMin: 500000,
    checkSizeMax: 50000000,
    stages: ['seed', 'series_a', 'series_b'],
    sectors: ['enterprise', 'consumer', 'fintech', 'crypto'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://greylock.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/greylock',
    notable_investments: ['LinkedIn', 'Facebook', 'Airbnb', 'Dropbox', 'Discord'],
  },
  {
    name: 'Kleiner Perkins',
    firm: 'Kleiner Perkins',
    type: 'vc',
    aum: 18000000000,
    checkSizeMin: 1000000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['software', 'healthcare', 'cleantech', 'fintech'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://www.kleinerperkins.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/kleiner-perkins-caufield-byers',
    notable_investments: ['Google', 'Amazon', 'Genentech', 'Twitter', 'Slack'],
  },
  {
    name: 'Lightspeed Venture Partners',
    firm: 'Lightspeed Venture Partners',
    type: 'vc',
    aum: 18000000000,
    checkSizeMin: 500000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['enterprise', 'consumer', 'fintech', 'healthcare'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://lsvp.com',
    source: 'SEC EDGAR, Company Website',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001837027',
    cik: '0001837027',
    notable_investments: ['Snap', 'Affirm', 'AppDynamics', 'Nutanix'],
  },
  {
    name: 'Index Ventures',
    firm: 'Index Ventures',
    type: 'vc',
    aum: 15000000000,
    checkSizeMin: 500000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['fintech', 'enterprise', 'marketplaces', 'gaming'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://www.indexventures.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/index-ventures',
    notable_investments: ['Robinhood', 'Figma', 'Discord', 'Notion', 'Plaid'],
  },
  {
    name: 'Bessemer Venture Partners',
    firm: 'Bessemer Venture Partners',
    type: 'vc',
    aum: 20000000000,
    checkSizeMin: 1000000,
    checkSizeMax: 75000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['software', 'healthcare', 'fintech', 'consumer'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://www.bvp.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/bessemer-venture-partners',
    notable_investments: ['Shopify', 'LinkedIn', 'Pinterest', 'Twilio', 'Yelp'],
  },
  {
    name: 'NEA (New Enterprise Associates)',
    firm: 'New Enterprise Associates',
    type: 'vc',
    aum: 25000000000,
    checkSizeMin: 500000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['healthcare', 'software', 'fintech', 'consumer'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://www.nea.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/new-enterprise-associates',
    notable_investments: ['Salesforce', 'Tableau', 'Uber', 'Coursera', 'Plaid'],
  },
  {
    name: 'General Catalyst',
    firm: 'General Catalyst',
    type: 'vc',
    aum: 25000000000,
    checkSizeMin: 500000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['software', 'fintech', 'healthcare', 'consumer'],
    location: { city: 'Cambridge', state: 'MA', country: 'USA' },
    website: 'https://www.generalcatalyst.com',
    source: 'SEC EDGAR, Company Website',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001837027',
    notable_investments: ['Stripe', 'Airbnb', 'Snap', 'Warby Parker', 'HubSpot'],
  },
  {
    name: 'Founders Fund',
    firm: 'Founders Fund',
    type: 'vc',
    aum: 11000000000,
    checkSizeMin: 500000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['software', 'aerospace', 'biotech', 'crypto'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://foundersfund.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/founders-fund',
    notable_investments: ['SpaceX', 'Palantir', 'Facebook', 'Stripe', 'Airbnb'],
  },
  {
    name: 'Khosla Ventures',
    firm: 'Khosla Ventures',
    type: 'vc',
    aum: 15000000000,
    checkSizeMin: 250000,
    checkSizeMax: 50000000,
    stages: ['seed', 'series_a', 'series_b'],
    sectors: ['cleantech', 'healthcare', 'ai', 'enterprise'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://www.khoslaventures.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/khosla-ventures',
    notable_investments: ['Square', 'DoorDash', 'Instacart', 'Affirm', 'OpenAI'],
  },
];

// ===========================================
// SEED & EARLY STAGE VCs
// Source: OpenVC, AngelList, Company Websites
// ===========================================

export const SEED_STAGE_VCS: PublicInvestor[] = [
  {
    name: 'First Round Capital',
    firm: 'First Round Capital',
    type: 'vc',
    aum: 1500000000,
    checkSizeMin: 500000,
    checkSizeMax: 3000000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'fintech', 'marketplaces', 'consumer'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://firstround.com',
    source: 'Company Website, OpenVC',
    sourceUrl: 'https://openvc.app/vc/first-round-capital',
    notable_investments: ['Uber', 'Square', 'Notion', 'Roblox'],
  },
  {
    name: 'Union Square Ventures',
    firm: 'Union Square Ventures',
    type: 'vc',
    aum: 2000000000,
    checkSizeMin: 500000,
    checkSizeMax: 25000000,
    stages: ['seed', 'series_a'],
    sectors: ['marketplaces', 'crypto', 'fintech', 'media'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://www.usv.com',
    source: 'Company Website, OpenVC',
    sourceUrl: 'https://www.usv.com/companies/',
    notable_investments: ['Twitter', 'Coinbase', 'Etsy', 'Tumblr', 'MongoDB'],
  },
  {
    name: 'Y Combinator',
    firm: 'Y Combinator',
    type: 'accelerator',
    aum: 3000000000,
    checkSizeMin: 125000,
    checkSizeMax: 500000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'fintech', 'healthcare', 'consumer', 'enterprise'],
    location: { city: 'Mountain View', state: 'CA', country: 'USA' },
    website: 'https://www.ycombinator.com',
    source: 'Company Website',
    sourceUrl: 'https://www.ycombinator.com/companies',
    notable_investments: ['Airbnb', 'Stripe', 'Dropbox', 'Reddit', 'Coinbase'],
  },
  {
    name: 'Initialized Capital',
    firm: 'Initialized Capital',
    type: 'vc',
    aum: 700000000,
    checkSizeMin: 250000,
    checkSizeMax: 3000000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'fintech', 'consumer'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://initialized.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/initialized-capital',
    notable_investments: ['Coinbase', 'Instacart', 'Flexport', 'Cruise'],
  },
  {
    name: 'Forerunner Ventures',
    firm: 'Forerunner Ventures',
    type: 'vc',
    aum: 1000000000,
    checkSizeMin: 500000,
    checkSizeMax: 15000000,
    stages: ['seed', 'series_a'],
    sectors: ['consumer', 'commerce', 'dtc'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://forerunnerventures.com',
    source: 'Company Website, OpenVC',
    sourceUrl: 'https://openvc.app/vc/forerunner-ventures',
    notable_investments: ['Dollar Shave Club', 'Glossier', 'Warby Parker', 'Away'],
  },
  {
    name: 'Floodgate',
    firm: 'Floodgate',
    type: 'vc',
    aum: 500000000,
    checkSizeMin: 250000,
    checkSizeMax: 3000000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'ai', 'consumer'],
    location: { city: 'Palo Alto', state: 'CA', country: 'USA' },
    website: 'https://floodgate.com',
    source: 'Company Website, OpenVC',
    sourceUrl: 'https://openvc.app/vc/floodgate',
    notable_investments: ['Lyft', 'Twitter', 'Twitch', 'Refinery29'],
  },
  {
    name: 'SV Angel',
    firm: 'SV Angel',
    type: 'vc',
    aum: 350000000,
    checkSizeMin: 100000,
    checkSizeMax: 1000000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'consumer', 'enterprise'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://svangel.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/sv-angel',
    notable_investments: ['Airbnb', 'Pinterest', 'Square', 'Stripe', 'GitHub'],
  },
  {
    name: 'Lerer Hippeau',
    firm: 'Lerer Hippeau',
    type: 'vc',
    aum: 800000000,
    checkSizeMin: 500000,
    checkSizeMax: 5000000,
    stages: ['seed', 'series_a'],
    sectors: ['consumer', 'media', 'commerce', 'healthcare'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://lererhippeau.com',
    source: 'Company Website, OpenVC',
    sourceUrl: 'https://openvc.app/vc/lerer-hippeau',
    notable_investments: ['Buzzfeed', 'Warby Parker', 'Casper', 'Allbirds'],
  },
  {
    name: 'Lowercase Capital',
    firm: 'Lowercase Capital',
    type: 'vc',
    aum: 300000000,
    checkSizeMin: 100000,
    checkSizeMax: 2000000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'consumer', 'fintech'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://lowercasecapital.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/lowercase-capital',
    notable_investments: ['Twitter', 'Uber', 'Instagram', 'Optimizely'],
  },
  {
    name: 'Slow Ventures',
    firm: 'Slow Ventures',
    type: 'vc',
    aum: 400000000,
    checkSizeMin: 100000,
    checkSizeMax: 2000000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'consumer', 'creator economy'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://slow.co',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/slow-ventures',
    notable_investments: ['Gumroad', 'Clubhouse', 'Figma'],
  },
  {
    name: 'Precursor Ventures',
    firm: 'Precursor Ventures',
    type: 'vc',
    aum: 200000000,
    checkSizeMin: 100000,
    checkSizeMax: 1000000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'fintech', 'healthcare'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://precursorvc.com',
    source: 'Company Website, OpenVC',
    sourceUrl: 'https://openvc.app/vc/precursor-ventures',
  },
  {
    name: 'Hustle Fund',
    firm: 'Hustle Fund',
    type: 'vc',
    aum: 150000000,
    checkSizeMin: 25000,
    checkSizeMax: 500000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'consumer', 'b2b'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://www.hustlefund.vc',
    source: 'Company Website, OpenVC',
    sourceUrl: 'https://openvc.app/vc/hustle-fund',
    email: 'pitch@hustlefund.vc',
  },
  {
    name: '500 Global',
    firm: '500 Global (500 Startups)',
    type: 'vc',
    aum: 2800000000,
    checkSizeMin: 50000,
    checkSizeMax: 500000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'fintech', 'consumer', 'enterprise'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://500.co',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/500-startups',
    notable_investments: ['Canva', 'Credit Karma', 'Grab', 'Udemy'],
  },
  {
    name: 'Techstars',
    firm: 'Techstars',
    type: 'accelerator',
    aum: 500000000,
    checkSizeMin: 20000,
    checkSizeMax: 120000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'fintech', 'healthcare', 'consumer'],
    location: { city: 'Boulder', state: 'CO', country: 'USA' },
    website: 'https://www.techstars.com',
    source: 'Company Website',
    sourceUrl: 'https://www.techstars.com/portfolio',
    notable_investments: ['SendGrid', 'ClassPass', 'DigitalOcean', 'Zipline'],
  },
];

// ===========================================
// GROWTH & LATE STAGE INVESTORS
// Source: SEC 13F, Company Websites
// ===========================================

export const GROWTH_INVESTORS: PublicInvestor[] = [
  {
    name: 'Insight Partners',
    firm: 'Insight Partners',
    type: 'vc',
    aum: 80000000000,
    checkSizeMin: 10000000,
    checkSizeMax: 500000000,
    stages: ['series_b', 'growth', 'buyout'],
    sectors: ['software', 'enterprise'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://www.insightpartners.com',
    source: 'SEC EDGAR 13F, Company Website',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001513699',
    cik: '0001513699',
    notable_investments: ['Twitter', 'Shopify', 'DocuSign', 'Qualtrics'],
  },
  {
    name: 'Tiger Global Management',
    firm: 'Tiger Global Management',
    type: 'hedge_fund',
    aum: 30000000000,
    checkSizeMin: 5000000,
    checkSizeMax: 500000000,
    stages: ['series_b', 'growth'],
    sectors: ['software', 'fintech', 'consumer'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://www.tigerglobal.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001167483',
    cik: '0001167483',
    notable_investments: ['Facebook', 'Spotify', 'Stripe', 'ByteDance'],
  },
  {
    name: 'Coatue Management',
    firm: 'Coatue Management',
    type: 'hedge_fund',
    aum: 48000000000,
    checkSizeMin: 10000000,
    checkSizeMax: 500000000,
    stages: ['series_b', 'growth'],
    sectors: ['software', 'fintech', 'consumer tech'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://www.coatue.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001535392',
    cik: '0001535392',
    notable_investments: ['Snap', 'DoorDash', 'Instacart', 'Airtable'],
  },
  {
    name: 'Addition',
    firm: 'Addition',
    type: 'vc',
    aum: 4000000000,
    checkSizeMin: 5000000,
    checkSizeMax: 200000000,
    stages: ['series_b', 'growth'],
    sectors: ['software', 'fintech', 'enterprise'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://www.addition.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/addition-management',
    notable_investments: ['Stripe', 'Plaid', 'Figma', 'Discord'],
  },
  {
    name: 'IVP (Institutional Venture Partners)',
    firm: 'IVP',
    type: 'vc',
    aum: 9000000000,
    checkSizeMin: 10000000,
    checkSizeMax: 100000000,
    stages: ['series_b', 'growth'],
    sectors: ['software', 'consumer', 'enterprise'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://www.ivp.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/institutional-venture-partners',
    notable_investments: ['Slack', 'Twitter', 'Dropbox', 'Snap', 'Discord'],
  },
  {
    name: 'Battery Ventures',
    firm: 'Battery Ventures',
    type: 'vc',
    aum: 13000000000,
    checkSizeMin: 1000000,
    checkSizeMax: 75000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['software', 'enterprise', 'industrial tech'],
    location: { city: 'Boston', state: 'MA', country: 'USA' },
    website: 'https://www.battery.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/battery-ventures',
    notable_investments: ['Groupon', 'Glassdoor', 'Wayfair', 'Coinbase'],
  },
  {
    name: 'Norwest Venture Partners',
    firm: 'Norwest Venture Partners',
    type: 'vc',
    aum: 12500000000,
    checkSizeMin: 5000000,
    checkSizeMax: 100000000,
    stages: ['series_a', 'series_b', 'growth'],
    sectors: ['software', 'healthcare', 'consumer'],
    location: { city: 'Palo Alto', state: 'CA', country: 'USA' },
    website: 'https://www.nvp.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/norwest-venture-partners',
    notable_investments: ['Uber', 'Spotify', 'Opendoor', 'Plaid'],
  },
];

// ===========================================
// PRIVATE EQUITY FIRMS
// Source: SEC EDGAR, Company Websites
// ===========================================

export const PE_FIRMS: PublicInvestor[] = [
  {
    name: 'Blackstone',
    firm: 'Blackstone Inc',
    type: 'pe',
    aum: 1000000000000,
    checkSizeMin: 100000000,
    checkSizeMax: 10000000000,
    stages: ['growth', 'buyout'],
    sectors: ['technology', 'real_estate', 'healthcare', 'infrastructure'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://www.blackstone.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001393818',
    cik: '0001393818',
    notable_investments: ['Ancestry', 'Refinitiv', 'Bumble'],
  },
  {
    name: 'KKR',
    firm: 'KKR & Co Inc',
    type: 'pe',
    aum: 528000000000,
    checkSizeMin: 50000000,
    checkSizeMax: 5000000000,
    stages: ['growth', 'buyout'],
    sectors: ['technology', 'healthcare', 'industrials', 'consumer'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://www.kkr.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001404912',
    cik: '0001404912',
    notable_investments: ['GoDaddy', 'ByteDance', 'Epic Games'],
  },
  {
    name: 'Apollo Global Management',
    firm: 'Apollo Global Management',
    type: 'pe',
    aum: 617000000000,
    checkSizeMin: 100000000,
    checkSizeMax: 10000000000,
    stages: ['growth', 'buyout', 'credit'],
    sectors: ['technology', 'media', 'industrials', 'financial_services'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://www.apollo.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001411494',
    cik: '0001411494',
  },
  {
    name: 'Carlyle Group',
    firm: 'The Carlyle Group',
    type: 'pe',
    aum: 426000000000,
    checkSizeMin: 50000000,
    checkSizeMax: 5000000000,
    stages: ['growth', 'buyout'],
    sectors: ['aerospace', 'defense', 'technology', 'healthcare'],
    location: { city: 'Washington', state: 'DC', country: 'USA' },
    website: 'https://www.carlyle.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001527166',
    cik: '0001527166',
  },
  {
    name: 'TPG',
    firm: 'TPG Inc',
    type: 'pe',
    aum: 135000000000,
    checkSizeMin: 25000000,
    checkSizeMax: 2000000000,
    stages: ['growth', 'buyout'],
    sectors: ['technology', 'healthcare', 'consumer'],
    location: { city: 'Fort Worth', state: 'TX', country: 'USA' },
    website: 'https://www.tpg.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001880661',
    cik: '0001880661',
    notable_investments: ['Airbnb', 'Spotify', 'Uber'],
  },
  {
    name: 'Thoma Bravo',
    firm: 'Thoma Bravo',
    type: 'pe',
    aum: 130000000000,
    checkSizeMin: 50000000,
    checkSizeMax: 5000000000,
    stages: ['growth', 'buyout'],
    sectors: ['software', 'technology'],
    location: { city: 'Chicago', state: 'IL', country: 'USA' },
    website: 'https://www.thomabravo.com',
    source: 'Company Website',
    sourceUrl: 'https://www.thomabravo.com/companies',
    notable_investments: ['McAfee', 'SolarWinds', 'Sophos', 'Dynatrace'],
  },
  {
    name: 'Vista Equity Partners',
    firm: 'Vista Equity Partners',
    type: 'pe',
    aum: 96000000000,
    checkSizeMin: 50000000,
    checkSizeMax: 5000000000,
    stages: ['growth', 'buyout'],
    sectors: ['software', 'enterprise'],
    location: { city: 'Austin', state: 'TX', country: 'USA' },
    website: 'https://www.vistaequitypartners.com',
    source: 'Company Website',
    sourceUrl: 'https://www.vistaequitypartners.com/companies/',
    notable_investments: ['Marketo', 'Cvent', 'Ping Identity', 'Pluralsight'],
  },
  {
    name: 'Silver Lake',
    firm: 'Silver Lake Partners',
    type: 'pe',
    aum: 100000000000,
    checkSizeMin: 100000000,
    checkSizeMax: 5000000000,
    stages: ['growth', 'buyout'],
    sectors: ['technology'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://www.silverlake.com',
    source: 'Company Website',
    sourceUrl: 'https://www.silverlake.com/companies/',
    notable_investments: ['Dell', 'Airbnb', 'Twitter', 'Alibaba'],
  },
];

// ===========================================
// HEDGE FUNDS WITH VC ARMS
// Source: SEC EDGAR 13F
// ===========================================

export const HEDGE_FUNDS: PublicInvestor[] = [
  {
    name: 'Citadel',
    firm: 'Citadel Advisors',
    type: 'hedge_fund',
    aum: 62000000000,
    checkSizeMin: 10000000,
    checkSizeMax: 1000000000,
    stages: ['growth', 'public'],
    sectors: ['technology', 'financials', 'healthcare'],
    location: { city: 'Chicago', state: 'IL', country: 'USA' },
    website: 'https://www.citadel.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001423053',
    cik: '0001423053',
  },
  {
    name: 'Bridgewater Associates',
    firm: 'Bridgewater Associates',
    type: 'hedge_fund',
    aum: 124000000000,
    checkSizeMin: 100000000,
    checkSizeMax: 5000000000,
    stages: ['public'],
    sectors: ['macro', 'diversified'],
    location: { city: 'Westport', state: 'CT', country: 'USA' },
    website: 'https://www.bridgewater.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001350694',
    cik: '0001350694',
  },
  {
    name: 'Two Sigma',
    firm: 'Two Sigma Investments',
    type: 'hedge_fund',
    aum: 60000000000,
    checkSizeMin: 10000000,
    checkSizeMax: 500000000,
    stages: ['growth', 'public'],
    sectors: ['technology', 'quantitative'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://www.twosigma.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001179392',
    cik: '0001179392',
  },
  {
    name: 'Renaissance Technologies',
    firm: 'Renaissance Technologies',
    type: 'hedge_fund',
    aum: 130000000000,
    checkSizeMin: 50000000,
    checkSizeMax: 2000000000,
    stages: ['public'],
    sectors: ['quantitative'],
    location: { city: 'East Setauket', state: 'NY', country: 'USA' },
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001037389',
    cik: '0001037389',
  },
  {
    name: 'D.E. Shaw',
    firm: 'D.E. Shaw & Co',
    type: 'hedge_fund',
    aum: 60000000000,
    checkSizeMin: 10000000,
    checkSizeMax: 1000000000,
    stages: ['growth', 'public'],
    sectors: ['technology', 'quantitative'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://www.deshaw.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001009207',
    cik: '0001009207',
  },
  {
    name: 'Millennium Management',
    firm: 'Millennium Management',
    type: 'hedge_fund',
    aum: 59000000000,
    checkSizeMin: 10000000,
    checkSizeMax: 500000000,
    stages: ['public'],
    sectors: ['multi-strategy'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://www.mlp.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001273087',
    cik: '0001273087',
  },
  {
    name: 'Point72',
    firm: 'Point72 Asset Management',
    type: 'hedge_fund',
    aum: 26000000000,
    checkSizeMin: 5000000,
    checkSizeMax: 500000000,
    stages: ['growth', 'public'],
    sectors: ['technology', 'healthcare'],
    location: { city: 'Stamford', state: 'CT', country: 'USA' },
    website: 'https://www.point72.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001603466',
    cik: '0001603466',
  },
  {
    name: 'Viking Global',
    firm: 'Viking Global Investors',
    type: 'hedge_fund',
    aum: 30000000000,
    checkSizeMin: 10000000,
    checkSizeMax: 500000000,
    stages: ['growth', 'public'],
    sectors: ['technology', 'healthcare'],
    location: { city: 'Greenwich', state: 'CT', country: 'USA' },
    website: 'https://www.vikingglobal.com',
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001103804',
    cik: '0001103804',
  },
  {
    name: 'Lone Pine Capital',
    firm: 'Lone Pine Capital',
    type: 'hedge_fund',
    aum: 16000000000,
    checkSizeMin: 10000000,
    checkSizeMax: 500000000,
    stages: ['growth', 'public'],
    sectors: ['technology', 'consumer'],
    location: { city: 'Greenwich', state: 'CT', country: 'USA' },
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001061768',
    cik: '0001061768',
  },
  {
    name: 'Dragoneer',
    firm: 'Dragoneer Investment Group',
    type: 'hedge_fund',
    aum: 22000000000,
    checkSizeMin: 25000000,
    checkSizeMax: 500000000,
    stages: ['series_c', 'growth'],
    sectors: ['technology', 'software'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://www.dragoneer.com',
    source: 'SEC EDGAR 13F, Company Website',
    sourceUrl: 'https://www.crunchbase.com/organization/dragoneer-investment-group',
    notable_investments: ['Snowflake', 'Slack', 'Spotify', 'Airbnb'],
  },
];

// ===========================================
// FAMILY OFFICES
// Source: SEC EDGAR, Forbes, Public Records
// ===========================================

export const FAMILY_OFFICES: PublicInvestor[] = [
  {
    name: 'Soros Fund Management',
    firm: 'Soros Fund Management',
    type: 'family_office',
    aum: 25000000000,
    checkSizeMin: 5000000,
    checkSizeMax: 500000000,
    stages: ['growth', 'public'],
    sectors: ['technology', 'healthcare', 'fintech'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001029160',
    cik: '0001029160',
  },
  {
    name: 'Duquesne Family Office',
    firm: 'Duquesne Family Office',
    type: 'family_office',
    aum: 15000000000,
    checkSizeMin: 10000000,
    checkSizeMax: 500000000,
    stages: ['growth', 'public'],
    sectors: ['technology', 'macro'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001536411',
    cik: '0001536411',
  },
  {
    name: 'Baupost Group',
    firm: 'Baupost Group',
    type: 'family_office',
    aum: 27000000000,
    checkSizeMin: 10000000,
    checkSizeMax: 500000000,
    stages: ['growth', 'public', 'distressed'],
    sectors: ['value', 'distressed'],
    location: { city: 'Boston', state: 'MA', country: 'USA' },
    source: 'SEC EDGAR 13F',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000916620',
    cik: '0000916620',
  },
  {
    name: 'Iconiq Capital',
    firm: 'Iconiq Capital',
    type: 'family_office',
    aum: 80000000000,
    checkSizeMin: 5000000,
    checkSizeMax: 200000000,
    stages: ['series_b', 'growth'],
    sectors: ['technology', 'software'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://www.iconiqcapital.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/iconiq-capital',
    notable_investments: ['Adyen', 'Datadog', 'Snowflake', 'Zoom'],
  },
  {
    name: 'Emerson Collective',
    firm: 'Emerson Collective',
    type: 'family_office',
    aum: 3500000000,
    checkSizeMin: 1000000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'growth'],
    sectors: ['education', 'immigration', 'climate', 'media'],
    location: { city: 'Palo Alto', state: 'CA', country: 'USA' },
    website: 'https://www.emersoncollective.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/emerson-collective',
    notable_investments: ['The Atlantic', 'Oscar Health', 'AltSchool'],
  },
];

// ===========================================
// CORPORATE VENTURE CAPITAL (CVCs)
// Source: Company Websites, CB Insights
// ===========================================

export const CORPORATE_VCS: PublicInvestor[] = [
  {
    name: 'Google Ventures (GV)',
    firm: 'GV (Google Ventures)',
    type: 'cvc',
    aum: 8000000000,
    checkSizeMin: 500000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['software', 'healthcare', 'ai', 'consumer'],
    location: { city: 'Mountain View', state: 'CA', country: 'USA' },
    website: 'https://www.gv.com',
    source: 'Company Website',
    sourceUrl: 'https://www.gv.com/portfolio/',
    notable_investments: ['Uber', 'Slack', 'Stripe', 'Nest', 'GitLab'],
  },
  {
    name: 'Intel Capital',
    firm: 'Intel Capital',
    type: 'cvc',
    aum: 15000000000,
    checkSizeMin: 1000000,
    checkSizeMax: 50000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['semiconductors', 'ai', 'cloud', 'iot'],
    location: { city: 'Santa Clara', state: 'CA', country: 'USA' },
    website: 'https://www.intelcapital.com',
    source: 'Company Website',
    sourceUrl: 'https://www.intelcapital.com/portfolio/',
    notable_investments: ['Cloudera', 'DocuSign', 'MongoDB', 'Snap'],
  },
  {
    name: 'Salesforce Ventures',
    firm: 'Salesforce Ventures',
    type: 'cvc',
    aum: 5000000000,
    checkSizeMin: 1000000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['enterprise', 'cloud', 'saas'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://www.salesforceventures.com',
    source: 'Company Website',
    sourceUrl: 'https://www.salesforceventures.com/portfolio/',
    notable_investments: ['DocuSign', 'Dropbox', 'Twilio', 'Zoom'],
  },
  {
    name: 'Microsoft M12',
    firm: 'M12 (Microsoft)',
    type: 'cvc',
    aum: 2000000000,
    checkSizeMin: 1000000,
    checkSizeMax: 50000000,
    stages: ['series_a', 'series_b', 'growth'],
    sectors: ['enterprise', 'ai', 'cloud', 'security'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://m12.vc',
    source: 'Company Website',
    sourceUrl: 'https://m12.vc/portfolio/',
    notable_investments: ['Grab', 'Cruise', 'Circle'],
  },
  {
    name: 'Nvidia GPU Ventures',
    firm: 'Nvidia',
    type: 'cvc',
    checkSizeMin: 1000000,
    checkSizeMax: 50000000,
    stages: ['series_a', 'series_b', 'growth'],
    sectors: ['ai', 'robotics', 'autonomous_vehicles', 'healthcare_ai'],
    location: { city: 'Santa Clara', state: 'CA', country: 'USA' },
    website: 'https://www.nvidia.com',
    source: 'Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/nvidia/recent_investments',
  },
  {
    name: 'Qualcomm Ventures',
    firm: 'Qualcomm Ventures',
    type: 'cvc',
    aum: 1500000000,
    checkSizeMin: 500000,
    checkSizeMax: 30000000,
    stages: ['seed', 'series_a', 'series_b'],
    sectors: ['mobile', '5g', 'iot', 'automotive'],
    location: { city: 'San Diego', state: 'CA', country: 'USA' },
    website: 'https://www.qualcommventures.com',
    source: 'Company Website',
    sourceUrl: 'https://www.qualcommventures.com/portfolio/',
  },
  {
    name: 'Comcast Ventures',
    firm: 'Comcast Ventures',
    type: 'cvc',
    checkSizeMin: 1000000,
    checkSizeMax: 50000000,
    stages: ['series_a', 'series_b', 'growth'],
    sectors: ['media', 'entertainment', 'consumer', 'enterprise'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://comcastventures.com',
    source: 'Company Website',
    sourceUrl: 'https://comcastventures.com/portfolio/',
  },
  {
    name: 'Citi Ventures',
    firm: 'Citi Ventures',
    type: 'cvc',
    checkSizeMin: 5000000,
    checkSizeMax: 50000000,
    stages: ['series_b', 'growth'],
    sectors: ['fintech', 'payments', 'blockchain'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://citi.com/ventures',
    source: 'Company Website',
    sourceUrl: 'https://www.citi.com/ventures/portfolio.html',
    notable_investments: ['Square', 'Chain', 'Betterment'],
  },
  {
    name: 'Goldman Sachs',
    firm: 'Goldman Sachs Growth Equity',
    type: 'cvc',
    checkSizeMin: 25000000,
    checkSizeMax: 500000000,
    stages: ['growth'],
    sectors: ['fintech', 'enterprise', 'healthcare'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://www.goldmansachs.com',
    source: 'SEC EDGAR',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000886982',
    cik: '0000886982',
  },
];

// ===========================================
// NOTABLE ANGEL INVESTORS
// Source: AngelList, LinkedIn, Public Press
// ===========================================

export const ANGEL_INVESTORS: PublicInvestor[] = [
  {
    name: 'Naval Ravikant',
    firm: 'AngelList',
    type: 'angel',
    checkSizeMin: 25000,
    checkSizeMax: 500000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'crypto', 'consumer'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://nav.al',
    source: 'AngelList, Public Press',
    sourceUrl: 'https://angel.co/naval',
    notable_investments: ['Twitter', 'Uber', 'AngelList', 'Notion'],
  },
  {
    name: 'Elad Gil',
    firm: 'Independent',
    type: 'angel',
    checkSizeMin: 100000,
    checkSizeMax: 5000000,
    stages: ['pre_seed', 'seed', 'series_a'],
    sectors: ['software', 'ai', 'biotech'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://eladgil.com',
    source: 'Personal Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/person/elad-gil',
    notable_investments: ['Airbnb', 'Coinbase', 'Instacart', 'Square', 'Stripe'],
  },
  {
    name: 'Ron Conway',
    firm: 'SV Angel',
    type: 'angel',
    checkSizeMin: 50000,
    checkSizeMax: 500000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'consumer', 'enterprise'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    source: 'Crunchbase, Public Press',
    sourceUrl: 'https://www.crunchbase.com/person/ron-conway',
    notable_investments: ['Google', 'Facebook', 'Twitter', 'Airbnb', 'Pinterest'],
  },
  {
    name: 'Reid Hoffman',
    firm: 'Greylock Partners',
    type: 'angel',
    checkSizeMin: 100000,
    checkSizeMax: 2000000,
    stages: ['seed', 'series_a'],
    sectors: ['software', 'ai', 'networks'],
    location: { city: 'Palo Alto', state: 'CA', country: 'USA' },
    linkedinUrl: 'https://www.linkedin.com/in/reidhoffman/',
    source: 'LinkedIn, Public Press',
    sourceUrl: 'https://www.crunchbase.com/person/reid-hoffman',
    notable_investments: ['Airbnb', 'Facebook', 'Zynga', 'Convoy'],
  },
  {
    name: 'Marc Andreessen',
    firm: 'Andreessen Horowitz',
    type: 'angel',
    checkSizeMin: 100000,
    checkSizeMax: 5000000,
    stages: ['seed', 'series_a'],
    sectors: ['software', 'crypto', 'media'],
    location: { city: 'Atherton', state: 'CA', country: 'USA' },
    source: 'Crunchbase, Public Press',
    sourceUrl: 'https://www.crunchbase.com/person/marc-andreessen',
    notable_investments: ['Facebook', 'Twitter', 'Skype', 'GitHub'],
  },
  {
    name: 'Chris Sacca',
    firm: 'Lowercase Capital',
    type: 'angel',
    checkSizeMin: 25000,
    checkSizeMax: 2000000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'consumer'],
    location: { city: 'Truckee', state: 'CA', country: 'USA' },
    source: 'Public Press, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/person/chris-sacca',
    notable_investments: ['Twitter', 'Uber', 'Instagram', 'Kickstarter'],
  },
  {
    name: 'Jason Calacanis',
    firm: 'Launch',
    type: 'angel',
    checkSizeMin: 25000,
    checkSizeMax: 100000,
    stages: ['pre_seed', 'seed'],
    sectors: ['software', 'consumer', 'saas'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://calacanis.com',
    source: 'Personal Website, AngelList',
    sourceUrl: 'https://angel.co/jasoncalacanis',
    email: 'jason@launch.co',
    notable_investments: ['Uber', 'Robinhood', 'Calm'],
  },
  {
    name: 'Ashton Kutcher',
    firm: 'Sound Ventures',
    type: 'angel',
    checkSizeMin: 100000,
    checkSizeMax: 5000000,
    stages: ['seed', 'series_a'],
    sectors: ['consumer', 'social', 'fintech'],
    location: { city: 'Los Angeles', state: 'CA', country: 'USA' },
    website: 'https://www.sound.vc',
    source: 'Company Website, Public Press',
    sourceUrl: 'https://www.sound.vc/portfolio',
    notable_investments: ['Airbnb', 'Uber', 'Spotify', 'Robinhood'],
  },
];

// ===========================================
// FINTECH FOCUSED VCs
// Source: OpenVC, Company Websites
// ===========================================

export const FINTECH_VCS: PublicInvestor[] = [
  {
    name: 'Ribbit Capital',
    firm: 'Ribbit Capital',
    type: 'vc',
    aum: 4000000000,
    checkSizeMin: 1000000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['fintech', 'insurtech', 'crypto'],
    location: { city: 'Palo Alto', state: 'CA', country: 'USA' },
    website: 'https://ribbitcap.com',
    source: 'Company Website, Crunchbase',
    sourceUrl: 'https://www.crunchbase.com/organization/ribbit-capital',
    notable_investments: ['Robinhood', 'Coinbase', 'Credit Karma', 'Nubank'],
  },
  {
    name: 'QED Investors',
    firm: 'QED Investors',
    type: 'vc',
    aum: 2500000000,
    checkSizeMin: 1000000,
    checkSizeMax: 50000000,
    stages: ['seed', 'series_a', 'series_b'],
    sectors: ['fintech', 'insurtech', 'proptech'],
    location: { city: 'Alexandria', state: 'VA', country: 'USA' },
    website: 'https://www.qedinvestors.com',
    source: 'Company Website',
    sourceUrl: 'https://www.qedinvestors.com/portfolio',
    notable_investments: ['Credit Karma', 'SoFi', 'Nubank', 'Klarna'],
  },
  {
    name: 'Nyca Partners',
    firm: 'Nyca Partners',
    type: 'vc',
    aum: 1500000000,
    checkSizeMin: 5000000,
    checkSizeMax: 50000000,
    stages: ['series_a', 'series_b', 'growth'],
    sectors: ['fintech', 'insurtech', 'enterprise_fintech'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://www.nycapartners.com',
    source: 'Company Website',
    sourceUrl: 'https://www.nycapartners.com/portfolio',
  },
  {
    name: 'Fintech Collective',
    firm: 'Fintech Collective',
    type: 'vc',
    aum: 350000000,
    checkSizeMin: 500000,
    checkSizeMax: 5000000,
    stages: ['seed', 'series_a'],
    sectors: ['fintech', 'insurtech', 'regtech'],
    location: { city: 'New York', state: 'NY', country: 'USA' },
    website: 'https://fintech.io',
    source: 'Company Website, OpenVC',
    sourceUrl: 'https://openvc.app/vc/fintech-collective',
  },
];

// ===========================================
// HEALTHCARE FOCUSED VCs
// Source: Company Websites, Crunchbase
// ===========================================

export const HEALTHCARE_VCS: PublicInvestor[] = [
  {
    name: 'a16z Bio',
    firm: 'Andreessen Horowitz Bio Fund',
    type: 'vc',
    aum: 2200000000,
    checkSizeMin: 1000000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b'],
    sectors: ['biotech', 'healthcare', 'life_sciences'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://a16z.com/bio-health/',
    source: 'Company Website',
    sourceUrl: 'https://a16z.com/portfolio/#checks=bio,Bio+%26+Health+Tech',
  },
  {
    name: 'ARCH Venture Partners',
    firm: 'ARCH Venture Partners',
    type: 'vc',
    aum: 7000000000,
    checkSizeMin: 1000000,
    checkSizeMax: 50000000,
    stages: ['seed', 'series_a', 'series_b'],
    sectors: ['biotech', 'life_sciences', 'healthcare'],
    location: { city: 'Chicago', state: 'IL', country: 'USA' },
    website: 'https://www.archventure.com',
    source: 'Company Website',
    sourceUrl: 'https://www.archventure.com/portfolio/',
    notable_investments: ['Illumina', 'Juno Therapeutics', 'Grail'],
  },
  {
    name: 'Flagship Pioneering',
    firm: 'Flagship Pioneering',
    type: 'vc',
    aum: 11600000000,
    checkSizeMin: 10000000,
    checkSizeMax: 200000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['biotech', 'healthcare', 'sustainability'],
    location: { city: 'Cambridge', state: 'MA', country: 'USA' },
    website: 'https://www.flagshippioneering.com',
    source: 'Company Website',
    sourceUrl: 'https://www.flagshippioneering.com/companies',
    notable_investments: ['Moderna', 'Seres Therapeutics', 'Indigo Agriculture'],
  },
  {
    name: 'GV Life Sciences',
    firm: 'GV (Google Ventures) Life Sciences',
    type: 'cvc',
    checkSizeMin: 1000000,
    checkSizeMax: 50000000,
    stages: ['seed', 'series_a', 'series_b'],
    sectors: ['healthcare', 'biotech', 'healthtech'],
    location: { city: 'Mountain View', state: 'CA', country: 'USA' },
    website: 'https://www.gv.com',
    source: 'Company Website',
    sourceUrl: 'https://www.gv.com/portfolio/',
  },
  {
    name: 'Rock Health',
    firm: 'Rock Health',
    type: 'vc',
    aum: 300000000,
    checkSizeMin: 500000,
    checkSizeMax: 5000000,
    stages: ['seed', 'series_a'],
    sectors: ['digital_health', 'healthtech'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://rockhealth.com',
    source: 'Company Website',
    sourceUrl: 'https://rockhealth.com/rock-health-venture-fund/',
  },
];

// ===========================================
// AI/ML FOCUSED VCs
// Source: Company Websites, OpenVC
// ===========================================

export const AI_VCS: PublicInvestor[] = [
  {
    name: 'a16z AI',
    firm: 'Andreessen Horowitz AI Fund',
    type: 'vc',
    aum: 3500000000,
    checkSizeMin: 1000000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['ai', 'ml', 'robotics'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://a16z.com',
    source: 'Company Website',
    sourceUrl: 'https://a16z.com/portfolio/',
  },
  {
    name: 'Radical Ventures',
    firm: 'Radical Ventures',
    type: 'vc',
    aum: 1000000000,
    checkSizeMin: 1000000,
    checkSizeMax: 30000000,
    stages: ['seed', 'series_a', 'series_b'],
    sectors: ['ai', 'ml', 'deep_tech'],
    location: { city: 'Toronto', country: 'Canada' },
    website: 'https://radical.vc',
    source: 'Company Website',
    sourceUrl: 'https://radical.vc/portfolio/',
  },
  {
    name: 'Air Street Capital',
    firm: 'Air Street Capital',
    type: 'vc',
    aum: 100000000,
    checkSizeMin: 500000,
    checkSizeMax: 5000000,
    stages: ['seed', 'series_a'],
    sectors: ['ai', 'ml', 'deep_tech'],
    location: { city: 'London', country: 'UK' },
    website: 'https://www.airstreet.com',
    source: 'Company Website',
    sourceUrl: 'https://www.airstreet.com/portfolio',
  },
];

// ===========================================
// CRYPTO/WEB3 FOCUSED VCs
// Source: Company Websites, Crunchbase
// ===========================================

export const CRYPTO_VCS: PublicInvestor[] = [
  {
    name: 'a16z Crypto',
    firm: 'Andreessen Horowitz Crypto',
    type: 'vc',
    aum: 7600000000,
    checkSizeMin: 1000000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['crypto', 'web3', 'defi', 'nft'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://a16zcrypto.com',
    source: 'Company Website',
    sourceUrl: 'https://a16zcrypto.com/portfolio/',
    notable_investments: ['Coinbase', 'OpenSea', 'Uniswap', 'Solana'],
  },
  {
    name: 'Paradigm',
    firm: 'Paradigm',
    type: 'vc',
    aum: 10000000000,
    checkSizeMin: 1000000,
    checkSizeMax: 500000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['crypto', 'web3', 'defi'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://www.paradigm.xyz',
    source: 'Company Website',
    sourceUrl: 'https://www.paradigm.xyz/portfolio',
    notable_investments: ['Coinbase', 'FTX', 'Uniswap', 'Optimism'],
  },
  {
    name: 'Polychain Capital',
    firm: 'Polychain Capital',
    type: 'vc',
    aum: 6500000000,
    checkSizeMin: 1000000,
    checkSizeMax: 100000000,
    stages: ['seed', 'series_a', 'series_b', 'growth'],
    sectors: ['crypto', 'web3', 'defi'],
    location: { city: 'San Francisco', state: 'CA', country: 'USA' },
    website: 'https://polychain.capital',
    source: 'Company Website',
    sourceUrl: 'https://polychain.capital/portfolio',
    notable_investments: ['Coinbase', 'Dfinity', 'Compound'],
  },
  {
    name: 'Pantera Capital',
    firm: 'Pantera Capital',
    type: 'vc',
    aum: 4500000000,
    checkSizeMin: 500000,
    checkSizeMax: 50000000,
    stages: ['seed', 'series_a', 'series_b'],
    sectors: ['crypto', 'blockchain', 'defi'],
    location: { city: 'Menlo Park', state: 'CA', country: 'USA' },
    website: 'https://panteracapital.com',
    source: 'Company Website',
    sourceUrl: 'https://panteracapital.com/portfolio/',
    notable_investments: ['Circle', 'Polkadot', 'Zcash'],
  },
  {
    name: 'Multicoin Capital',
    firm: 'Multicoin Capital',
    type: 'vc',
    aum: 1000000000,
    checkSizeMin: 1000000,
    checkSizeMax: 50000000,
    stages: ['seed', 'series_a', 'series_b'],
    sectors: ['crypto', 'web3', 'defi'],
    location: { city: 'Austin', state: 'TX', country: 'USA' },
    website: 'https://multicoin.capital',
    source: 'Company Website',
    sourceUrl: 'https://multicoin.capital/portfolio/',
    notable_investments: ['Solana', 'Helium', 'The Graph'],
  },
];

// ===========================================
// AGGREGATE ALL INVESTORS
// ===========================================

export const ALL_PUBLIC_INVESTORS: PublicInvestor[] = [
  ...TIER1_VCS,
  ...SEED_STAGE_VCS,
  ...GROWTH_INVESTORS,
  ...PE_FIRMS,
  ...HEDGE_FUNDS,
  ...FAMILY_OFFICES,
  ...CORPORATE_VCS,
  ...ANGEL_INVESTORS,
  ...FINTECH_VCS,
  ...HEALTHCARE_VCS,
  ...AI_VCS,
  ...CRYPTO_VCS,
];

// Export counts for UI
export const INVESTOR_COUNTS = {
  tier1_vcs: TIER1_VCS.length,
  seed_stage: SEED_STAGE_VCS.length,
  growth: GROWTH_INVESTORS.length,
  pe: PE_FIRMS.length,
  hedge_funds: HEDGE_FUNDS.length,
  family_offices: FAMILY_OFFICES.length,
  cvcs: CORPORATE_VCS.length,
  angels: ANGEL_INVESTORS.length,
  fintech: FINTECH_VCS.length,
  healthcare: HEALTHCARE_VCS.length,
  ai: AI_VCS.length,
  crypto: CRYPTO_VCS.length,
  total: ALL_PUBLIC_INVESTORS.length,
};
